"""document

Revision ID: 8e22851423b7
Revises: 4c9b966f1673
Create Date: 2025-12-08 20:54:42.458912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '8e22851423b7'
down_revision: Union[str, None] = '4c9b966f1673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_author')),
    sa.UniqueConstraint('email', name=op.f('uq_author_email'))
    )
    op.create_table('tag',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag')),
    sa.UniqueConstraint('name', name=op.f('uq_tag_name'))
    )
    op.create_table('document',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_type', sa.Enum('TEXT', 'PDF', 'MARKDOWN', 'HTML', name='documenttype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='documentstatus'), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['appuser.id'], name=op.f('fk_document_owner_id_appuser'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document'))
    )
    op.create_index(op.f('ix_document_title'), 'document', ['title'], unique=False)
    op.create_table('document_authors',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], name=op.f('fk_document_authors_author_id_author'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_document_authors_document_id_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'author_id', name=op.f('pk_document_authors'))
    )
    op.create_table('document_tags',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_document_tags_document_id_document'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_document_tags_tag_id_tag'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'tag_id', name=op.f('pk_document_tags'))
    )
    op.create_table('document_version',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['appuser.id'], name=op.f('fk_document_version_created_by_id_appuser'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_document_version_document_id_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_version'))
    )
    op.create_table('pdf_document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('pdf_version', sa.String(length=10), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('is_searchable', sa.Boolean(), nullable=False),
    sa.Column('pdf_title', sa.String(length=500), nullable=True),
    sa.Column('pdf_author', sa.String(length=255), nullable=True),
    sa.Column('pdf_subject', sa.String(length=500), nullable=True),
    sa.Column('pdf_creator', sa.String(length=255), nullable=True),
    sa.Column('pdf_producer', sa.String(length=255), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modification_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('text_preview', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['document.id'], name=op.f('fk_pdf_document_id_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pdf_document'))
    )
    op.create_table('text_document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('encoding', sa.String(length=50), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('character_count', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('content_preview', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['document.id'], name=op.f('fk_text_document_id_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_text_document'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_document')
    op.drop_table('pdf_document')
    op.drop_table('document_version')
    op.drop_table('document_tags')
    op.drop_table('document_authors')
    op.drop_index(op.f('ix_document_title'), table_name='document')
    op.drop_table('document')
    op.drop_table('tag')
    op.drop_table('author')
    # ### end Alembic commands ###
